video: "full.mp4"

output_jsonl_relative_file_path: "football_output.jsonl"
real_data_jsonl_relative_file_path: "tracking-produced.jsonl"

yolo:
  model: "yolov8n-football.pt"
  selected_class_ids:
    ball:
      id: 0
      confidence_threshold: 0.1
    goalkeeper:
      id: 1
      confidence_threshold: 0.5
    player:
      id: 2
      confidence_threshold: 0.5


byte_track:
  track_activation_threshold: 0.25
  lost_track_buffer: 50
  minimum_matching_threshold: 0.8
  frame_rate: 25
  minimum_consecutive_frames: 1
