video: "full.mp4"

yolo:
  model: "yolov8n-football.pt"
  confidence_threshold: 0.5
  selected_class_ids:
    ball: 0
    goalkeeper: 1
    player: 2


byte_track:
  track_activation_threshold: 0.25
  lost_track_buffer: 50
  minimum_matching_threshold: 0.8
  frame_rate: 25
  minimum_consecutive_frames: 1
